deployment:
  tasks:
    - export REPO=/home/studsmut/repositories/studiostarlight
    - export LIVE=/home/studsmut/public_html

    - /usr/local/bin/composer --working-dir=$REPO install --no-dev --optimize-autoloader

    # copy web assets
    - /bin/rsync -av --delete --exclude=".git" $REPO/public/  $LIVE/

    # copy vendor + app inside public_html
    - /bin/rsync -av --delete --exclude=".git" $REPO/vendor/  $LIVE/vendor/
    - /bin/rsync -av --delete --exclude=".git" $REPO/app/     $LIVE/app/
