<?php
declare(strict_types=1);

require dirname(__DIR__) . '/vendor/autoload.php';

/**
 * --------------------------------------------------------------------------
 *  Simple front-controller router (Task 9)
 * --------------------------------------------------------------------------
 *  – Maps clean paths to stub handlers for now.
 *  – Next tasks will swap the stubs for real controllers + views.
 */

$uri = trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/');

/** @var array<string, callable> */
$routes = [
    ''         => fn() => page('Home'),
    'blog'     => fn() => page('Blog'),
    'gallery'  => fn() => page('Gallery'),
    'shop'     => fn() => page('Shop'),
    'about'    => fn() => page('About Us'),
];

// Run the route or show 404
if (isset($routes[$uri])) {
    echo $routes[$uri]();   // ← echo the page string
} else {
    http_response_code(404);
    echo page('404 Not Found', '<p>The page you requested does not exist.</p>');
}


/**
 * Very thin “view” helper until we build real layouts.
 */
function page(string $title, string $body = ''): string
{
    ob_start();
    $content = $body ?: "<p class=\"text-mutedBlue\">Stub page generated by router (Task 9).</p>";
    require dirname(__DIR__) . '/app/Views/layouts/main.php';
    return ob_get_clean();
}

